# Generated by Django 2.2.10 on 2020-02-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_original_price', models.CharField(max_length=100)),
                ('item_discount_price', models.CharField(max_length=100)),
                ('item_discount_rate', models.CharField(max_length=100)),
                ('item_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
